@url = http://localhost:5000/api
@id = 8389aa15-c161-416e-8d46-7d982cd13e23
@parkingSpotId = 00000000-0000-0000-0000-000000000004

###
GET {{url}}


###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{id}}

###
POST {{url}}/reservations/vehicle
Content-Type: application/json

{
   "ParkingSpotId":"{{parkingSpotId}}",
   "EmployeeName":"mateusz",
   "LicensePlate":"KR8EP3",
   "Date":"2023-09-27"
}
###
POST {{url}}/reservations/cleaning
Content-Type: application/json

{
   "Date":"2023-09-27"
}

###
POST {{url}}/reservations
Content-Type: application/json

{
   "ParkingSpotName":"P1",
   "EmployeeName":"mateusz",
   "LicensePlate":"KR8EP3"
}

###
PUT  {{url}}/reservations/{{id}}
Content-Type: application/json

{
   "LicensePlate":"KR8EP35"
}

###
DELETE   {{url}}/reservations/{{id}}
