@url = http://localhost:5000/api
@id = 8389aa15-c161-416e-8d46-7d982cd13e23
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}


###
GET {{url}}/parkingspots

###
GET {{url}}/reservations/{{id}}

###
POST {{url}}/parkingspots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
   "ParkingSpotId":"{{parkingSpotId}}",
   "EmployeeName":"mateusz3",
   "LicensePlate":"XXYY1234",
   "Date":"2023-08-30",
   "capacity":1
}
###
POST {{url}}/parkingspots/reservations/cleaning
Content-Type: application/json

{
   "Date":"2023-09-11"
}

###
POST {{url}}/reservations
Content-Type: application/json

{
   "ParkingSpotName":"P1",
   "EmployeeName":"mateusz",
   "LicensePlate":"KR8EP3"
}

###
PUT  {{url}}/reservations/{{id}}
Content-Type: application/json

{
   "LicensePlate":"KR8EP35"
}

###
DELETE   {{url}}/reservations/{{id}}

###
POST {{url}}/users
Content-Type: application/json

{
   "email":"test@tewst.pl",
   "username":"test",
   "fullname":"test test",
   "role":"role1",
   "password":"test"
}

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
   "email":"test@tewst.pl",
   "password":"test"
}

###
GET {{url}}/users/dc60edd4-8a5a-45eb-b4c3-5088cce9b89d

###
GET {{url}}/users/test@tewst.pl

###
GET {{url}}/users/jwt

@token = {{sign_in.response.body.$.accessToken}}
###
GET {{url}}/users/me
Content-Type: application/json
Authorization: Bearer {{token}}
